name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # ‚Üê GANTI INI (dari ubuntu-latest)

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy app
        run: |
          cd ~/forumThreads-API
          git pull origin main
          npm run migrate:prod up
          docker compose down
          docker compose up -d --build --remove-orphans
          docker compose ps